// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/tenant.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/tuannguyenandpadcojp/go-training/lqm/week7/day1/internal/db"
)

// MockTenantDB is a mock of TenantDB interface.
type MockTenantDB struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDBMockRecorder
}

// MockTenantDBMockRecorder is the mock recorder for MockTenantDB.
type MockTenantDBMockRecorder struct {
	mock *MockTenantDB
}

// NewMockTenantDB creates a new mock instance.
func NewMockTenantDB(ctrl *gomock.Controller) *MockTenantDB {
	mock := &MockTenantDB{ctrl: ctrl}
	mock.recorder = &MockTenantDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDB) EXPECT() *MockTenantDBMockRecorder {
	return m.recorder
}

// GetTenantByName mocks base method.
func (m *MockTenantDB) GetTenantByName(name string) (*db.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByName", name)
	ret0, _ := ret[0].(*db.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByName indicates an expected call of GetTenantByName.
func (mr *MockTenantDBMockRecorder) GetTenantByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByName", reflect.TypeOf((*MockTenantDB)(nil).GetTenantByName), name)
}
